language: python
python:  
  - "2.7"  

before_install:
  - "sudo add-apt-repository ppa:v-launchpad-jochen-sprickerhof-de/pcl -y"
  - "sudo apt-get update"
  - "sudo apt-get -q -y install libpcl-all"
  - "pip install cython -q"
  - "pip install coverage"
  
install:
  - "make all"

script:
  - "make test"


after_script:
  # Send the code coverage to the scrutinizer-CI service
  - "pip install scrutinizer-ocular"
  - "ocular"
